### ISSUE TITLE
Jinja Attributes

### ISSUE THREAD

**Issue by Skalldihor** [benmezger/shiny-robot#2]
Hello, I put new Jinja syntax in project.

in file: idp/confs/idp.properties

{{ idp_EntityID }}
-- is url server destination install idp, and the endpoint /idp/shibboleth
-- example:  https://idp.organization.com/idp/shibboleth

{{ store_pwd }}
-- This is to Sealer store, not sealer keystore.

**Comment by benmezger** [comment]
Commit d483093d3ac30656b93272e9a234709691defef4 fixes this issue.
